name: Random Pronoun Change

on:
  schedule:
    - cron: '0 * * * *' # Run every day at midnight (UTC)

jobs:
  change-pronouns:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Random Pronouns
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          const core = require('@actions/core');
          const github = require('@actions/github');

          try {
            const pronouns = ['he/him', 'she/her', 'they/them']; // Add more if needed
            const randomIndex = Math.floor(Math.random() * pronouns.length);
            const selectedPronouns = pronouns[randomIndex];

            const octokit = github.getOctokit(process.env.GITHUB_TOKEN);
            await octokit.users.updateAuthenticated({ name: selectedPronouns });

            console.log(`Updated pronouns to: ${selectedPronouns}`);
          } catch (error) {
            core.setFailed(error.message);
          }